apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
#   googleCloudBuild:
#     projectId: ticketing-dev-281319
  artifacts:
    - image: juandkpa/auth
      context: packages/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
