apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
    useDockerCLI: true
#   googleCloudBuild:
#     projectId: ticketing-dev-281319
  artifacts:
    - image: juandkpa/auth
      docker:
        dockerfile: Dockerfile
        target: auth
        buildArgs:
          artifact: 'auth'
      sync:
        manual:
          - src: 'packages/auth/src/**/*.ts'
            dest: .
    - image: juandkpa/client
      docker:
        dockerfile: Dockerfile
        target: client
      sync:
        manual:
          - src: 'packages/client/**/*.js'
            dest: .
